import os
import json
import xgboost as xgb
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# Initialize API
app = FastAPI(
    title="EnergySignal AI Inference Engine",
    description="Production 15-min Day-Ahead Power Forecasting API",
    version="1.0.0"
)

# Paths for the artifacts generated by GitHub Actions
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_PATH = os.path.join(BASE_DIR, 'models', 'xgb_baseline.json')
METRICS_PATH = os.path.join(BASE_DIR, 'models', 'metrics.json')

model = xgb.XGBRegressor()

@app.on_event("startup")
def load_artifacts():
    """Loads model weights on startup if they exist."""
    if os.path.exists(MODEL_PATH):
        model.load_model(MODEL_PATH)

class FeaturePayload(BaseModel):
    hour: int
    minute: int
    day_of_week: int
    month: int
    is_holiday: int
    is_15min_era: int
    price_lag_1h: float
    price_lag_24h: float
    price_lag_168h: float
    volatility_24h: float
    total_renewable: float
    renewable_penetration: float
    residual_load: float
    temperature_2m: float
    wind_speed_10m: float
    solar_irradiance: float

@app.get("/health")
def health_check():
    return {"status": "healthy", "model_ready": os.path.exists(MODEL_PATH)}

@app.get("/metrics")
def get_quant_metrics():
    """Serves the institutional metrics calculated during the daily CI run."""
    try:
        if not os.path.exists(METRICS_PATH):
            return {"status": "pending", "message": "Metrics being calculated by GitHub Actions"}
        with open(METRICS_PATH, 'r') as f:
            return json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/forecast")
def generate_forecast(payload: FeaturePayload):
    """Generates a 24h forward price prediction for a single 15-min block."""
    if not os.path.exists(MODEL_PATH):
        raise HTTPException(status_code=503, detail="Model weights not yet deployed.")
    try:
        input_data = pd.DataFrame([payload.model_dump()])
        prediction = float(model.predict(input_data))
        return {
            "predicted_price_eur_mwh": round(prediction, 2),
            "horizon": "24h_ahead",
            "resolution": "15-minute MTU"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
